import type { LangCode } from '@/context/Translations';

export interface LanguageItem {
  code: LangCode;
  name: string;
  native: string;
  flag: string;
  reviewed: boolean;
}

export const ALL_LANGUAGES: LanguageItem[] = [
  // ── Indian Languages ──
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', reviewed: true },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', reviewed: true },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳', reviewed: true },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', reviewed: true },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳', reviewed: true },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳', reviewed: true },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳', reviewed: true },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳', reviewed: true },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳', reviewed: true },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳', reviewed: true },
  { code: 'ur', name: 'Urdu', native: 'اردو', flag: '🇮🇳', reviewed: true },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ', flag: '🇮🇳', reviewed: false },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া', flag: '🇮🇳', reviewed: false },
  { code: 'ne', name: 'Nepali', native: 'नेपाली', flag: '🇮🇳', reviewed: false },
  { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्', flag: '🇮🇳', reviewed: false },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي', flag: '🇮🇳', reviewed: false },
  { code: 'mai', name: 'Maithili', native: 'मैथिली', flag: '🇮🇳', reviewed: false },
  { code: 'kok', name: 'Konkani', native: 'कोंकणी', flag: '🇮🇳', reviewed: false },
  { code: 'doi', name: 'Dogri', native: 'डोगरी', flag: '🇮🇳', reviewed: false },
  { code: 'ks', name: 'Kashmiri', native: 'کٲشُر', flag: '🇮🇳', reviewed: false },

  // ── East & Southeast Asia ──
  { code: 'zh', name: 'Chinese (Simplified)', native: '中文 (简体)', flag: '🇨🇳', reviewed: true },
  { code: 'zh-TW', name: 'Chinese (Traditional)', native: '中文 (繁體)', flag: '🇹🇼', reviewed: false },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵', reviewed: true },
  { code: 'ko', name: 'Korean', native: '한국어', flag: '🇰🇷', reviewed: true },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳', reviewed: false },
  { code: 'th', name: 'Thai', native: 'ไทย', flag: '🇹🇭', reviewed: false },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩', reviewed: true },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾', reviewed: true },
  { code: 'tl', name: 'Filipino / Tagalog', native: 'Tagalog', flag: '🇵🇭', reviewed: false },
  { code: 'my', name: 'Burmese', native: 'မြန်မာစာ', flag: '🇲🇲', reviewed: false },
  { code: 'km', name: 'Khmer', native: 'ខ្មែរ', flag: '🇰🇭', reviewed: false },
  { code: 'lo', name: 'Lao', native: 'ລາວ', flag: '🇱🇦', reviewed: false },
  { code: 'mn', name: 'Mongolian', native: 'Монгол', flag: '🇲🇳', reviewed: false },
  { code: 'si', name: 'Sinhala', native: 'සිංහල', flag: '🇱🇰', reviewed: false },

  // ── Middle East & Central Asia ──
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦', reviewed: true },
  { code: 'fa', name: 'Persian / Farsi', native: 'فارسی', flag: '🇮🇷', reviewed: false },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', flag: '🇹🇷', reviewed: false },
  { code: 'he', name: 'Hebrew', native: 'עברית', flag: '🇮🇱', reviewed: false },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî', flag: '🇮🇶', reviewed: false },
  { code: 'ps', name: 'Pashto', native: 'پښتو', flag: '🇦🇫', reviewed: false },
  { code: 'az', name: 'Azerbaijani', native: 'Azərbaycan', flag: '🇦🇿', reviewed: false },
  { code: 'kk', name: 'Kazakh', native: 'Қазақша', flag: '🇰🇿', reviewed: false },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbekcha', flag: '🇺🇿', reviewed: false },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն', flag: '🇦🇲', reviewed: false },
  { code: 'ka', name: 'Georgian', native: 'ქართული', flag: '🇬🇪', reviewed: false },

  // ── European Languages ──
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', reviewed: true },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', reviewed: true },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', reviewed: true },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹', reviewed: true },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇧🇷', reviewed: true },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺', reviewed: true },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱', reviewed: false },
  { code: 'pl', name: 'Polish', native: 'Polski', flag: '🇵🇱', reviewed: false },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', flag: '🇺🇦', reviewed: false },
  { code: 'ro', name: 'Romanian', native: 'Română', flag: '🇷🇴', reviewed: false },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷', reviewed: false },
  { code: 'cs', name: 'Czech', native: 'Čeština', flag: '🇨🇿', reviewed: false },
  { code: 'sv', name: 'Swedish', native: 'Svenska', flag: '🇸🇪', reviewed: false },
  { code: 'hu', name: 'Hungarian', native: 'Magyar', flag: '🇭🇺', reviewed: false },
  { code: 'da', name: 'Danish', native: 'Dansk', flag: '🇩🇰', reviewed: false },
  { code: 'fi', name: 'Finnish', native: 'Suomi', flag: '🇫🇮', reviewed: false },
  { code: 'no', name: 'Norwegian', native: 'Norsk', flag: '🇳🇴', reviewed: false },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰', reviewed: false },
  { code: 'bg', name: 'Bulgarian', native: 'Български', flag: '🇧🇬', reviewed: false },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷', reviewed: false },
  { code: 'sr', name: 'Serbian', native: 'Српски', flag: '🇷🇸', reviewed: false },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹', reviewed: false },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮', reviewed: false },
  { code: 'lv', name: 'Latvian', native: 'Latviešu', flag: '🇱🇻', reviewed: false },
  { code: 'et', name: 'Estonian', native: 'Eesti', flag: '🇪🇪', reviewed: false },
  { code: 'is', name: 'Icelandic', native: 'Íslenska', flag: '🇮🇸', reviewed: false },
  { code: 'ga', name: 'Irish', native: 'Gaeilge', flag: '🇮🇪', reviewed: false },
  { code: 'sq', name: 'Albanian', native: 'Shqip', flag: '🇦🇱', reviewed: false },
  { code: 'bs', name: 'Bosnian', native: 'Bosanski', flag: '🇧🇦', reviewed: false },
  { code: 'mk', name: 'Macedonian', native: 'Македонски', flag: '🇲🇰', reviewed: false },
  { code: 'mt', name: 'Maltese', native: 'Malti', flag: '🇲🇹', reviewed: false },
  { code: 'ca', name: 'Catalan', native: 'Català', flag: '🇪🇸', reviewed: false },
  { code: 'gl', name: 'Galician', native: 'Galego', flag: '🇪🇸', reviewed: false },
  { code: 'eu', name: 'Basque', native: 'Euskara', flag: '🇪🇸', reviewed: false },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', reviewed: false },
  { code: 'be', name: 'Belarusian', native: 'Беларуская', flag: '🇧🇾', reviewed: false },

  // ── African Languages ──
  { code: 'sw', name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪', reviewed: false },
  { code: 'am', name: 'Amharic', native: 'አማርኛ', flag: '🇪🇹', reviewed: false },
  { code: 'ha', name: 'Hausa', native: 'Hausa', flag: '🇳🇬', reviewed: false },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá', flag: '🇳🇬', reviewed: false },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo', flag: '🇳🇬', reviewed: false },
  { code: 'zu', name: 'Zulu', native: 'isiZulu', flag: '🇿🇦', reviewed: false },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa', flag: '🇿🇦', reviewed: false },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans', flag: '🇿🇦', reviewed: false },
  { code: 'so', name: 'Somali', native: 'Soomaaliga', flag: '🇸🇴', reviewed: false },
  { code: 'mg', name: 'Malagasy', native: 'Malagasy', flag: '🇲🇬', reviewed: false },
  { code: 'sn', name: 'Shona', native: 'chiShona', flag: '🇿🇼', reviewed: false },
  { code: 'om', name: 'Oromo', native: 'Afaan Oromoo', flag: '🇪🇹', reviewed: false },
  { code: 'ti', name: 'Tigrinya', native: 'ትግርኛ', flag: '🇪🇹', reviewed: false },
  { code: 'rw', name: 'Kinyarwanda', native: 'Ikinyarwanda', flag: '🇷🇼', reviewed: false },
  { code: 'ny', name: 'Chichewa', native: 'Chichewa', flag: '🇲🇼', reviewed: false },

  // ── Americas & Others ──
  { code: 'ht', name: 'Haitian Creole', native: 'Kreyòl Ayisyen', flag: '🇭🇹', reviewed: false },
  { code: 'haw', name: 'Hawaiian', native: 'ʻŌlelo Hawaiʻi', flag: '🇺🇸', reviewed: false },
  { code: 'la', name: 'Latin', native: 'Latina', flag: '🇻🇦', reviewed: false },
  { code: 'eo', name: 'Esperanto', native: 'Esperanto', flag: '🌐', reviewed: false },
  { code: 'yi', name: 'Yiddish', native: 'ייִדיש', flag: '🇮🇱', reviewed: false },
  { code: 'mi', name: 'Maori', native: 'Te Reo Māori', flag: '🇳🇿', reviewed: false },
  { code: 'sm', name: 'Samoan', native: 'Gagana Samoa', flag: '🇼🇸', reviewed: false },
  { code: 'qu', name: 'Quechua', native: 'Runa Simi', flag: '🇵🇪', reviewed: false },
  { code: 'gn', name: 'Guarani', native: 'Avañeʼẽ', flag: '🇵🇾', reviewed: false },
  { code: 'ay', name: 'Aymara', native: 'Aymar aru', flag: '🇧🇴', reviewed: false },
];
