-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZmivDNqLXP06mTo9
PAQBdepmez3mm8oD20ZA12wRUJKgCgYIKoZIzj0DAQehRANCAAT45+KCxcjoBXmP
aLBMoC0zvRgZcKJZ3W95UdvzWnWupeehOIRY/5y/htxIqdcopbeTYFwA5CTofuOT
VDKVLlJ0
-----END PRIVATE KEY-----