import * as Print from 'expo-print';
import type { AnalyzeResult } from '@/services/reportsApi';

export async function generateReportPdf(report: AnalyzeResult): Promise<string> {
  const {
    patientName,
    hospitalName,
    reportTypeFull,
    date,
    healthScore,
    healthLabel,
    values,
  } = report;

  let summaryObj: any = {};
  try {
    summaryObj = typeof report.summary === 'string' ? JSON.parse(report.summary) : report.summary;
  } catch (e) {
    // Ignore
  }

  const aiSummary = summaryObj.ai_summary || summaryObj.patient_friendly_explanation || 'No summary available.';

  // Build values table
  const tableRows = values.map(v => {
    let color = '#1e293b'; // normal
    if (v.status === 'high') color = '#dc2626';
    if (v.status === 'low') color = '#ea580c';
    return `
      <tr>
        <td>${v.name}</td>
        <td style="color: ${color}; font-weight: 600;">${v.value}</td>
        <td>${v.range}</td>
      </tr>
    `;
  }).join('');

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${reportTypeFull} Report</title>
      <style>
        body {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          color: #1e293b;
          padding: 40px;
          line-height: 1.5;
        }
        .header {
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #0f172a;
          margin: 0 0 10px 0;
          font-size: 28px;
        }
        .meta {
          color: #64748b;
          font-size: 14px;
        }
        .meta strong {
          color: #334155;
        }
        .score-card {
          background-color: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 24px;
          text-align: center;
          margin-bottom: 30px;
        }
        .score {
          font-size: 36px;
          font-weight: bold;
          color: #059669;
          margin-bottom: 8px;
        }
        .label {
          font-size: 16px;
          color: #475569;
          text-transform: uppercase;
          letter-spacing: 1px;
        }
        .summary {
          background-color: #f0fdf4;
          border-left: 4px solid #16a34a;
          padding: 16px 20px;
          margin-bottom: 30px;
          border-radius: 0 8px 8px 0;
        }
        .summary h3 {
          margin: 0 0 10px 0;
          color: #166534;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th, td {
          border: 1px solid #e2e8f0;
          padding: 12px 16px;
          text-align: left;
        }
        th {
          background-color: #f8fafc;
          font-weight: 700;
          color: #475569;
          text-transform: uppercase;
          font-size: 12px;
          letter-spacing: 0.5px;
        }
        tr:nth-child(even) {
          background-color: #f8fafc;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${reportTypeFull || 'Health Report'}</h1>
        <div class="meta">
          <strong>Patient:</strong> ${patientName || 'Unknown'} &nbsp;|&nbsp;
          <strong>Lab:</strong> ${hospitalName || 'Unknown'} &nbsp;|&nbsp;
          <strong>Date:</strong> ${date || new Date().toLocaleDateString()}
        </div>
      </div>

      <div class="score-card">
        <div class="score">${healthScore}/100</div>
        <div class="label">${healthLabel}</div>
      </div>

      <div class="summary">
        <h3>AI Analysis Summary</h3>
        <p style="margin: 0; color: #15803d;">${aiSummary}</p>
      </div>

      <h3 style="color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px;">Detailed Lab Values</h3>
      <table>
        <thead>
          <tr>
            <th>Test Name</th>
            <th>Result</th>
            <th>Normal Range</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows || '<tr><td colspan="3" style="text-align:center; color:#94a3b8;">No detailed lab values available</td></tr>'}
        </tbody>
      </table>
      
      <div style="margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center;">
        <p>Generated by HealthAI Care Hub • For informational purposes only</p>
      </div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}
